version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: increase
    groups:
      codemirror:
        patterns:
          - "@codemirror/*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
